window.GALERIA_FOLDERS = [
  {
    name: "Obras de Cre-Arte",
    folder: "Obras de Cre-Arte",
    files: [
      "Murga del Tomate- 2017- Arte x =.webp",
      "Descanaval- 2017- Arte x = (21).webp",
      "Descanaval- 2017- Arte x = (24).webp",
      "Descanaval- 2017- Arte x = (27).webp",
      "Descanaval- 2017- Arte x = (38).webp",
      "Descanaval- 2017- Arte x = (54).webp",
      "Descanaval- 2017- Arte x = (63).webp",
      "Fractales- 2017. Arte x = (1).webp",
      "Fractales- 2017. Arte x = (7).webp",
      "Lo que predece- 2017- Arte x =  (10).webp",
      "Lo que predece- 2017- Arte x =  (1).webp",
      "Murga del Tomate- 2017- Arte x = (2).webp",
      "Murga del Tomate- 2017- Arte x = (3).webp",
      "Zapandanga- 2017- Arte x = (17).webp",
      "Zapandanga- 2017- Arte x = (29).webp",
    ]
  },
  {
    name: "Talleres",
    folder: "talleres",
    files: [
      "talleres2.webp",
      "talleres3.webp",
      "talleres4.webp",
      "talleres5.webp",
      "talleres6.webp",
      "talleres7.webp",
      "talleres8.webp",
      "talleres9.webp",
      "talleres10.webp",
      "talleres11.webp",
      "talleres12.webp",
      "talleres13.webp",
      "talleres14.webp",
      "talleres15.webp",
      "talleres16.webp",
      "talleres17.webp",
      "lucestalleres.webp",
      "talleres19.webp",
      "talleres20.webp",
      "talleres21.webp",
      "talleres22.webp",
      "talleres23.webp",
      "talleres24.webp",
      "talleres25.webp",
      "talleres26.webp",
      "talleres27.webp",
      "talleres28.webp",
      "talleres29.webp",
      "talleres30.webp",
      "talleres31.webp",
      "talleres32.webp",
      "talleres33.webp",
      "talleres34.webp",
      "talleres35.webp",
      "talleres36.webp",
      "talleres37.webp",
      "talleres38.webp",
      "talleres39.webp",
      "talleres40.webp",
      "talleres41.webp",
      "talleres42.webp",
    ]
  },
  {
    name: "Viajes y Europa",
    folder: "viajes y europa",
    files: [
      "2015 - Reggio Emilia- Gira en Europa (1).webp",
      "2015 - Reggio Emilia- Gira en Europa (2).webp",
      "2015 - Reggio Emilia- Gira en Europa (3).webp",
      "2015 - Reggio Emilia- Gira en Europa (4).webp",
      "2015- Madrid- Gira en Europa (1).webp",
      "2015- Madrid- Gira en Europa (2).webp",
      "2015- Roma- Tiempo de amar- Gira en Europa (1).webp",
      "2015- Roma- Tiempo de amar- Gira en Europa (2).webp",
      "2015- Roma- Tiempo de amar- Gira en Europa (3).webp",
      "2015- Roma- Tiempo de amar- Gira en Europa (4).webp",
      "2015- Roma- Tiempo de amar- Gira en Europa (5).webp",
      "2015- Roma- Tiempo de amar- Gira en Europa (6).webp",
      "2015- Segovia- Tiempo de amar- Gira en Europa (1).webp",
      "2015- Segovia- Tiempo de amar- Gira en Europa (2).webp",
      "2015- Segovia- Tiempo de amar- Gira en Europa (3).webp",
      "2015- Segovia- Tiempo de amar- Gira en Europa (4).webp",
      "2015- Segovia- Tiempo de amar- Gira en Europa (5).webp",
      "2015- Segovia- Tiempo de amar- Gira en Europa (6).webp",
    ]
  },
  {
    name: "Entrenarte y Linea Sur",
    folder: "Entrenarte y Linea Sur ",
    files: [
      "2024- Viaje a Ramos Mexia (1).webp",
      "2024- Viaje a Ramos Mexia (2).webp",
      "2025- Viaje a Jacobacci (1).webp",
      "2025- Viaje a Jacobacci (2).webp",
      "2025- Viaje a Jacobacci (3).webp",
      "2025- Viaje a Jacobacci (4).webp",
    ]
  }
];
